### ISSUE TITLE
Possible omission of "peer_roles" in the Join Response

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#146]
When defining the Join Response in [0], it is currently said that `peer_roles` MUST be present if `creds` is also present.

As discussed with @ciseng at the ACE interim meeting on 2022-09-12 [1] and further offline, it would be better for the Pub-Sub profile of ACE [2] to not necessarily include this parameter. That's because it would just be a repetitive and unnecessary source of overhead in the Join Response, where "publisher" would practically be the only role of the current group members to be indicated anyway.

Therefore, the bullet point defining `peer_roles` in [0] can be changed as follows.

OLD:
> 'peer_roles', MUST be present if 'creds' is also present, otherwise it MUST NOT be present. This parameter is a CBOR array of n elements, with n the number of authentication credentials included in the 'creds' parameter (at most the number of members in the group).  The i-th element of the array specifies the role (or CBOR array of roles) that the group member associated with the i-th authentication credential in 'creds' has in the group. In particular, each array element is encoded as the role element of a scope entry, as defined in Section 3.1.

NEW:
> 'peer_roles', SHOULD be present if 'creds' is also present, otherwise it MUST NOT be present. This parameter is a CBOR array of n elements, with n the number of authentication credentials included in the 'creds' parameter (at most the number of members in the group). The i-th element of the array specifies the role (or CBOR array of roles) that the group member associated with the i-th authentication credential in 'creds' has in the group. In particular, each array element is encoded as the role element of a scope entry, as defined in Section 3.1.
> 
>  This parameter MAY be omitted if all the group members associated with the authentication credentials specified in the 'creds' parameter have the same role in the group joined by the Client, and such a role can be unambiguously assumed by the Client (e.g., based on what is defined in the used application profile of this specification).

[0] https://datatracker.ietf.org/doc/html/draft-ietf-ace-key-groupcomm-16#section-4.3.1

[1] https://datatracker.ietf.org/meeting/interim-2022-ace-01/session/ace

[2] https://datatracker.ietf.org/doc/draft-ietf-ace-pubsub-profile/

**Comment by chrysn** [comment]
**If** CCSes already need to encode the in their scope claim which role they take in the group, then let's please extend that exception to *any* situation in which the peer roles already follow from information that are available elsewhere (be it as a claim in the CCS or because there is only one value to them anyway).

I'm putting that "if" in bold because it's an actual "if": I'd be just as happy with CCSes that are really just the RPK plus curve numbers, and then my point would be moot.

(I don't care about doing the same on CWTs and [CX]509 credentials -- once they're around, the join response is already lugging around like 3x the amount of data it needs to, and while it may make sense in the interest of simplicity to be more general, it doesn't change much)

\<rant>oscore-groupcomm went through a [lot of trouble](https://eprint.iacr.org/2021/509) making sure we only need to transport and store 32 bytes instead of 64 bytes of data per peer. Any more per-peer data, in particularly signatures on non-CCS credentials, invalidate that effort.\</rant>
