### ISSUE TITLE
Section 3.3.3 - rename "rsnonce" to be more KDC-specific

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#68]

**Comment by fpalombini** [comment]
@jimsch 

I don't agree with this comment as the goal of section 3.3.3. is to define a more general "rsnonce" ace parameter. The fact that it is used in this specification by the kdc (which acts as RS) does not mean that other specification will take the same terminology. I would keep as is.

**Comment by jimsch** [comment]
So at the moment, I am saving the rs nonce value in two different locations, once for the OSCORE context creation and once for the KDC.  What I worry about is that I might need to keep the two values sync-ed together depending on if one gets updated by the KDC but not for the security layer.  As long as we don't believe that the two values are tied after they are received/generated the first time then this is not an issue.  If however, the KDC is generating new rsnonce values and that needs to be propigated elsewhere then that is a problem.

**Comment by fpalombini** [comment]
@jimsch if you are talking about the nonce N2 sent by RS to C during the OSCORE profile (https://tools.ietf.org/html/draft-ietf-ace-oscore-profile-10#section-4.2.1) then yes, they are absolutely separate and should not be tied together.
The "rsnonce" defined here does not need to be propagated elsewhere.

**Comment by jimsch** [comment]
Ok - so you are saying in this case there is not a problem, however if you are making this a general purpose rs nonce then if you have two applications that use this value the exact same situation is going to develop.

**Comment by fpalombini** [comment]
I had to think about this a bit (and go over it with Marco) but I see the problem now: the issue is not with the name itself, but with the *purpose* of the parameter. By defining a *general* parameter, we are opening up for interoperability issues between applications that use this same parameter in 2 different applications running at the same time. The problem is then how to differentiate between those 2 (which one is used with each application). It could be solved, but I guess it's not worth the headache. I will remove the generality (make it specialised to ace key groupcomm) and change the name to reflect that.

(Just for record, the reason for wanting to register a more general rsnonce is that we are already registering client and server nonces with specific functions in the OSCORE profile, and the cnonce defined in ace also has a very specific function, so I was thinking let's register *one* parameter that can be used as rs nonce by the application and let the application decide how to use it, rather than keep registering nonces for specific functions).

**Comment by jimsch** [comment]
I completely understand the impulse.  It is one that I have frequently and if this was not a nonce I would probably applaud the impulse.  The problem is the "once" piece.

Change looked fine to me.

**Comment by fpalombini** [comment]
following the discussion at the interim, I changed it to "kdcchallenge" in 99d3076fc3.
