### ISSUE TITLE
Section 7 - Expand the first paragraph.

### ISSUE THREAD

**Issue by marco-tiloca-sics** [ace-wg/ace-key-groupcomm#88]

**Comment by fpalombini** [comment]
So, the additional detail should cover:

- A mechanism like Appendix B.2 of OSCORE are useful in case of lost of context and reboot, so that the recipient can be on the safe side.

- If the group is rekeying, the time window between the end of the rekeying and a next loss of context is safe to go. A group rekeying puts the recipients on the safe side.

Is that it?
